spring:
  application:
    name: tccUnisagrado
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://localhost:1433;databaseName=tcc
    username: sa
    password: mudar123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true