spring:
  application:
    name: finchestagio
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://localhost:1433;databaseName=tcc
    username: sa
    password: mudar123
#    url: jdbc:sqlserver://localhost:1433;databaseName=tcc
#    username: sa
#    password: Kiria75475668
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2-console

marketplace:
  mercadolivre:
    url: https://www.mercadolivre.com.br/